### PR TITLE
feat(JavaScript): Allow changing action URL and more improvements

### PR DESCRIPTION
**Pull request by SilbinaryWolf**
* Change submit button(s) to change state on submit rather than on click (fixes bug where button disables for HTML5 validation)
* If field updating is a "select" tag type, replace it's "option" elements and trigger an update for Chosen/Select2. This is to avoid losing JS hooks on a form on the frontend.
* Add missing this._super() calls.
* Removed $this->owner->setForm(), the call makes no sense and caused a recursive loop when calling $this->owner->Link().

### CODE REVIEW

**Comment by SilbinaryWolf** [comment]
Also just an FYI, this is for my MultiRecordField module:
https://github.com/SilbinaryWolf/multirecordfield/tree/feat-displaylogicsupport

It needs to be able to rewrite the action URL so it can feed through the field.

**Comment by SilbinaryWolf** [comment]
@sheadawson Any time to look over this?

**Comment by sheadawson** [comment]
Soory @SilbinaryWolf looks like I started but didn't submit my feedback, see above

**Comment by sheadawson** [comment]
Thanks for this work :)

**Comment by SilbinaryWolf** [comment]
It wasn't used anywhere. I'm guessing I used it before I fixed the setForm() bug, then I proceeded to not use that property. Fixed now!

**Comment by sheadawson** [comment]
Cool thought that might be the case, cheers!

**Pull request merged**
